name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Build
        shell: bash
        run: |
          mvn package --no-transfer-progress --batch-mode
