name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Cache Maven packages
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Build
        shell: bash
        run: |
          mvn package --no-transfer-progress --batch-mode
